FPS = 10

RESOURCE_CELL_RESOURCE_COST = 150

OUTPOST_CREATION_RESOURCE_COST = 10
OUTPOST_MAX_HEALTH = 10
OUTPOST_MONEY_GAIN_INTERVAL = 3
OUTPOST_MONEY_GAIN_ENERGY_COST = OUTPOST_MONEY_GAIN_INTERVAL * FPS
OUTPOST_MONEY_GAIN_AMOUNT = 1
OUTPOST_REQUIRED_SUPPORT = 2
OUTPOST_WITHER_INTERVAL = 4
OUTPOST_WITHER_ENERGY_COST = OUTPOST_WITHER_INTERVAL * FPS