STANDARD = "standard"
STANDARD_CONSTRUCTION_AVAILABLE = "standard, ca"
RESOURCE_CELL_SELECTED = "resource cell selected"
RESOURCE_CELL_SELECTED_ROUTE_CREATION = "RC selected, route create"
RESOURCE_CELL_SELECTED_OUTPOST_CREATION = "RC selected, ind. outpost"

CURSOR_MOVE_STATES = [STANDARD, STANDARD_CONSTRUCTION_AVAILABLE, RESOURCE_CELL_SELECTED_ROUTE_CREATION, RESOURCE_CELL_SELECTED_OUTPOST_CREATION]
GAME_TICK_STATES = [STANDARD, STANDARD_CONSTRUCTION_AVAILABLE, RESOURCE_CELL_SELECTED_ROUTE_CREATION, RESOURCE_CELL_SELECTED_OUTPOST_CREATION]

STATE_HELPTEXT_DICT = {
	STANDARD: "Press [enter] to select, or arrow keys to move",
	STANDARD_CONSTRUCTION_AVAILABLE: "Press [enter] to select, or arrow keys to move",
	RESOURCE_CELL_SELECTED: "[1] attempt route, [2] individual outpost create, or [escape] to cancel",
	RESOURCE_CELL_SELECTED_ROUTE_CREATION: "[enter] to confirm route, [escape] to cancel",
	RESOURCE_CELL_SELECTED_OUTPOST_CREATION: "[enter] to create outpost here"
}

STATE_HELPTEXT2_DICT = {
	STANDARD_CONSTRUCTION_AVAILABLE: "Construct (cost): [1] Resource Cell (150)",
}

MONEY_DISPLAY_TEXT = "Money Available: {0:d}"